# Generated by Django 4.0.3 on 2022-03-15 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bb', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='declaration',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tanks', 'tanks'), ('hills', 'hills'), ('dd', 'dd'), ('Merchants', 'merchants'), ('Guildmasters', 'guildmasters'), ('Questgivers', 'questgivers'), ('Blacksmiths', 'blacksmiths'), ('Tanners', 'tanners'), ('Zelievars', 'zelievars'), ('SpellMasters', 'spellMasters')], default='tanks', max_length=25, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bulletin_file/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='text',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='commenter'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='declaration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_declaration', to='bb.declaration', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(max_length=3000, verbose_name='Comment'),
        ),
    ]
