# Generated by Django 4.0.3 on 2022-03-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='accounts/image/%Y/%m/%d', verbose_name='Avatar'),
        ),
    ]
